# Generated by Django 4.0.6 on 2022-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacionamento', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('numero_vaga', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status_vaga', models.BooleanField(default=False)),
            ],
        ),
    ]
