# Generated by Django 4.0.6 on 2022-12-31 03:54

import delivery.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident', '0002_remove_morador_condominio_remove_morador_numeros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(default=None, max_length=15, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(default=None, max_length=6)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, unique_for_date=True)),
                ('status', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(auto_now=True, null=True)),
                ('duracao', models.DurationField(blank=True, default=None, editable=False, null=True)),
                ('casas', models.ForeignKey(auto_created=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa')),
                ('modulo', models.ForeignKey(default=delivery.models.Box, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.box')),
                ('moradors', models.ForeignKey(auto_created=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador')),
                ('recebido_por', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
