# Generated by Django 4.0.6 on 2022-12-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_remove_morador_condominio_remove_morador_numeros_and_more'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='moradors',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='casas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa'),
        ),
    ]
