# Generated by Django 4.0.6 on 2022-12-31 04:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_remove_delivery_moradors_alter_delivery_casas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='duracao',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recebido_por',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
