# Generated by Django 4.0.6 on 2022-12-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_delivery_duracao_alter_delivery_recebido_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='casas',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='nota_fiscal',
            field=models.CharField(default=None, max_length=6, verbose_name='Nota Fiscal'),
        ),
    ]
