# Generated by Django 4.0.6 on 2023-01-03 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_remove_casa_condominio_remove_casa_morador_and_more'),
        ('delivery', '0006_rename_moradores_delivery_morador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='morador',
        ),
        migrations.AddField(
            model_name='delivery',
            name='numero_casa',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa'),
        ),
    ]
