# Generated by Django 4.0.6 on 2023-01-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_casa_condominio'),
        ('delivery', '0009_delivery_morador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='morador',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='numero_casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa'),
        ),
    ]
