# Generated by Django 4.0.6 on 2023-01-03 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_casa_condominio'),
        ('delivery', '0010_remove_delivery_morador_alter_delivery_numero_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='numero_casa',
        ),
        migrations.AddField(
            model_name='delivery',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador'),
        ),
    ]
