# Generated by Django 4.0.6 on 2023-02-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_remove_morador_casa_morador_numero_casa_morador_rua_and_more'),
        ('delivery', '0011_remove_delivery_numero_casa_delivery_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='data_retirada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resident.morador'),
        ),
    ]
