# Generated by Django 4.0.6 on 2023-02-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_delivery_morador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='morador',
        ),
    ]
