# Generated by Django 4.0.6 on 2023-02-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_remove_morador_condominio'),
        ('delivery', '0014_remove_delivery_morador'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador'),
        ),
    ]
