# Generated by Django 4.0.6 on 2023-02-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_alter_delivery_morador_delete_morador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='morador',
            new_name='moradores',
        ),
    ]
