# Generated by Django 4.0.6 on 2023-02-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0009_alter_morador_condominio'),
        ('delivery', '0018_rename_morador_delivery_moradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='moradores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resident.morador'),
        ),
    ]
