# Generated by Django 4.0.6 on 2023-02-19 23:38

import delivery.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0011_remove_morador_condominio_remove_morador_numero_casa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0020_remove_delivery_moradores_delivery_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='modulo',
            field=models.ForeignKey(default=delivery.models.Box, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='delivery.box'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='morador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='resident.moradia'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recebido_por',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
