# Generated by Django 4.0.6 on 2023-02-23 03:30

import delivery.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident', '0015_alter_morador_morador'),
        ('delivery', '0022_alter_delivery_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='modulo',
            field=models.ForeignKey(default=delivery.models.Box, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.box'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='morador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.moradia'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='recebido_por',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
