# Generated by Django 4.0.6 on 2023-02-23 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0024_alter_delivery_modulo_alter_delivery_morador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
