# Generated by Django 4.0.6 on 2022-12-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=None, max_length=4, null=True)),
                ('rua', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=200, null=True)),
                ('sobrenome', models.CharField(default=None, max_length=200, null=True)),
                ('telefone', models.CharField(default=None, max_length=40, null=True)),
                ('email', models.CharField(default=None, max_length=200, null=True, verbose_name='E-mail')),
                ('aceite_alertas', models.BooleanField(default=False, verbose_name='Aceita receber mensagens')),
                ('link_whats', models.CharField(default=None, editable=False, max_length=100, null=True)),
                ('condominio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio')),
                ('numeros', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa')),
            ],
        ),
    ]
