# Generated by Django 4.0.6 on 2022-12-31 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='numeros',
        ),
        migrations.AddField(
            model_name='casa',
            name='condominio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio'),
        ),
        migrations.AddField(
            model_name='casa',
            name='morador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero',
            field=models.CharField(default=None, max_length=4, null=True, verbose_name='Número da casa'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='rua',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Nome da rua'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Nome do condominio'),
        ),
    ]
