# Generated by Django 4.0.6 on 2023-01-03 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_remove_morador_condominio_remove_morador_numeros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='morador',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='link_whats',
        ),
        migrations.AddField(
            model_name='morador',
            name='casa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.casa'),
        ),
        migrations.AddField(
            model_name='morador',
            name='condominio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio'),
        ),
    ]
