# Generated by Django 4.0.6 on 2023-01-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_remove_casa_condominio_remove_casa_morador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='condominio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio'),
        ),
    ]
