# Generated by Django 4.0.6 on 2023-01-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_delivery_numero_casa_delivery_morador'),
        ('resident', '0004_casa_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='casa',
        ),
        migrations.AddField(
            model_name='morador',
            name='numero_casa',
            field=models.CharField(default=None, max_length=4, null=True, verbose_name='Número da casa'),
        ),
        migrations.AddField(
            model_name='morador',
            name='rua',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Nome da rua'),
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
