# Generated by Django 4.0.6 on 2023-02-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_remove_morador_casa_morador_numero_casa_morador_rua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='condominio',
        ),
    ]
