# Generated by Django 4.0.6 on 2023-02-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_remove_morador_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='aceite_alertas',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='rua',
        ),
    ]
