# Generated by Django 4.0.6 on 2023-02-19 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_remove_morador_aceite_alertas_remove_morador_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='aceite_alertas',
            field=models.BooleanField(default=False, verbose_name='Aceita receber mensagens'),
        ),
        migrations.AddField(
            model_name='morador',
            name='condominio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio'),
        ),
        migrations.AddField(
            model_name='morador',
            name='rua',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Nome da rua'),
        ),
    ]
