# Generated by Django 4.0.6 on 2023-02-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0009_alter_morador_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio'),
        ),
    ]
