# Generated by Django 4.0.6 on 2023-02-19 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident', '0010_alter_morador_condominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='rua',
        ),
        migrations.AddField(
            model_name='morador',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Moradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_moradia', models.CharField(default=None, max_length=4, null=True, verbose_name='Número da casa')),
                ('rua', models.CharField(default=None, max_length=50, null=True, verbose_name='Nome da rua')),
                ('bairro', models.CharField(default=None, max_length=100)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio')),
                ('morador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.morador')),
            ],
        ),
    ]
