# Generated by Django 4.0.6 on 2023-02-19 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0011_remove_morador_condominio_remove_morador_numero_casa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moradia',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='moradia',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='aceite_alertas',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='usuario',
        ),
    ]
