# Generated by Django 4.0.6 on 2023-02-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0012_remove_moradia_bairro_remove_moradia_rua_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moradia',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='moradia',
            name='morador',
        ),
        migrations.AddField(
            model_name='morador',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.condominio', verbose_name='Nome do condomínio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morador',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.moradia'),
        ),
    ]
