# Generated by Django 4.0.6 on 2023-02-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0013_remove_moradia_condominio_remove_moradia_morador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='morador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.moradia'),
        ),
    ]
