# Generated by Django 4.0.6 on 2023-02-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0014_alter_morador_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='morador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.moradia'),
        ),
    ]
