# Generated by Django 4.0.6 on 2022-12-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField(default=None)),
                ('hora_visita', models.TimeField(default=None)),
                ('nome', models.CharField(default=None, max_length=300, null=True)),
                ('sobrenome', models.CharField(default=None, max_length=300, null=True)),
                ('documento', models.CharField(default=None, max_length=100, null=True)),
                ('cpf', models.CharField(default=None, max_length=100, null=True)),
                ('veiculo', models.CharField(default=None, max_length=100, null=True)),
                ('autorizar_convidado', models.BooleanField(default=False)),
                ('anfitriao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador')),
            ],
        ),
        migrations.CreateModel(
            name='local_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('anfitriao_visita', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.morador')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.convidado')),
            ],
        ),
        migrations.CreateModel(
            name='lista_convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lista', models.CharField(default=None, max_length=100)),
                ('convidados_lista', models.ManyToManyField(to='guests.convidado')),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(default=None, max_length=20)),
                ('data_evento', models.DateTimeField(default=None)),
                ('qtd_convidados', models.CharField(default=None, max_length=3)),
                ('aceite_condicoes', models.BooleanField(default=False)),
                ('convidados_evento', models.ManyToManyField(to='guests.convidado')),
                ('local_eventos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='guests.local_evento')),
            ],
        ),
    ]
